{{- range $.Values.cluster.nodes.masters }}
apiVersion: v1
kind: Secret
metadata:
  name: bmc-{{ $.Values.cluster.name }}-{{ .site }}-{{ .name }}
  namespace: {{ $.Values.cluster.name }}
data:
  username: {{ .bmc_username | b64enc }}
  password: {{ .bmc_password | b64enc }}
type: Opaque
---
{{- end }}