---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.cluster.name }}-wait-lso-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ $.Values.cluster.name }}-wait-lso-job
          image: {{ $.Values.global.gitops.hook_image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "OCS PreSync Hook"
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "InstallSucceeded" ]; do
                echo "Waiting for the AI Operator to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get csv -n openshift-local-storage -l operators.coreos.com/local-storage-operator.openshift-local-storage='' -o jsonpath={..status.conditions[-1:].reason} )
              done
              # LABEL nodes
              {{- range $.Values.cluster.nodes }}
                {{- range . }}
              NODE_NAME=$(oc get nodes | egrep {{ .name }} | awk '{print $1}')
                  {{- if eq .lso "true" }}
              oc label node $NODE_NAME ran.openshift.io/lso=''
                  {{- end }}
                {{- end }}
              {{- end }}
              echo "All done! Hooray!"


