---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ $.Values.cluster.name }}
  namespace: {{ $.Values.cluster.name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  clusterNamespace: {{ $.Values.cluster.name }}
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: false
  iamPolicyController:
    enabled: false
  policyController:
    enabled: true
  searchCollector:
    enabled: false 
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ $.Values.cluster.name }}
spec:
  hubAcceptsClient: true
---
apiVersion: internal.open-cluster-management.io/v1beta1
kind: ManagedClusterInfo
metadata:
  name: compact
  namespace: compact
spec:
  #loggingCA: >-
  #  "PlaceHolderIgnored"
  masterEndpoint: https://api.{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}:6443
