apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'gitops-install-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}'
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  destination:
    namespace: {{ $.Values.global.gitops.namespace }}
    server: 'https://api.{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}:6443'
  project: default
  source:
    repoURL: '{{ $.Values.cluster.git_url }}'
    path: bp-cluster/gitops-install
    targetRevision: HEAD
    helm:
      valueFiles:
      - "{{ $.Values.global.values_location }}"
      - "{{ $.Values.mgmt.values_location }}"
      - "/values.yaml"
  syncPolicy:
    automated:
      allowEmpty: true
      # prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 3m
      limit: -1
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
