---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-local-storage
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "4.10"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: {{ coalesce $.Values.cluster.operator_source $.Values.global.mirror.operator_source }}
  sourceNamespace: openshift-marketplace
