---
kind: Secret
apiVersion: v1
metadata:
  name: repo-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}
  namespace: {{ $.Values.global.gitops.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  password: {{ $.Values.global.git_token | b64enc }}
  type: Z2l0
  url: {{ $.Values.cluster.git_url | b64enc | indent 2 }}
  username: {{ $.Values.global.git_user | b64enc }}
type: Opaque
