---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ $.Values.global.gitops.service_account }}-role
rules:
  - apiGroups:
    - "*"
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - extensions
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - apps
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - certificates.k8s.io
    resources: ["certificatesigningrequests/approval"]
    verbs:
    - impersonate
    resourceNames:
    - cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.gitops.service_account }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.global.gitops.service_account }}-role
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.gitops.service_account }}
    namespace: {{ $.Values.global.gitops.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.gitops.service_account }}-adm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.gitops.service_account }}
    namespace: {{ $.Values.global.gitops.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.global.gitops.service_account }}
  namespace: {{ $.Values.global.gitops.namespace }}