---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ $.Values.global.gitops.namespace }}-custom-role
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.global.gitops.namespace }}-custom-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.global.gitops.namespace }}-custom-role
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.global.gitops.namespace }}-argocd-application-controller
    namespace: {{ $.Values.global.gitops.namespace }}
  - kind: ServiceAccount
    name: {{ $.Values.global.gitops.namespace }}-argocd-server
    namespace: {{ $.Values.global.gitops.namespace }}
