---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: postinstall-{{ $.Values.cluster.name }}-add-registry-ca-wait-job
  namespace: {{ $.Values.global.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.global.gitops.service_account }}
      serviceAccountName: {{ $.Values.global.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.global.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.cluster.name }}-add-registry-ca-wait-job
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local CA to the global one."
              CONFIG_MAP="Pausing $SLEEP seconds..."
              while [ "$CONFIG_MAP" != "registry-ca-local" ]; do
                echo "Waiting for the CA ConfigMap to be defined. ($CONFIG_MAP)"
                sleep $SLEEP
                CONFIG_MAP=$( oc get ConfigMap -n openshift-config registry-ca-local -o jsonpath={..metadata.name} )
              done
              # Add it to the  additionalTrustedCA
              oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"registry-ca-local"}}}' --type=merge
              #
              ##### With ACM we use the full merged secret so cluster will get it at deploy time now
              #echo "Adding local pull secret to the global one."
              #cd /tmp
              #oc extract secret/pull-secret -n openshift-config --confirm
              #cat .dockerconfigjson | \
              #    jq --compact-output '.auths["{{ $.Values.global.registry.url }}/{{ $.Values.global.registry.user }}"] |= . + {"auth":"{{ printf "%s:%s" $.Values.global.registry.user $.Values.global.registry.password | b64enc  }}"}' \
              #    > new_dockerconfigjson
              #oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=new_dockerconfigjson
              #rm -f .dockerconfigjson new_dockerconfigjson
              echo "All done! Hooray!"
